import React, { useContext, useState, useEffect } from 'react';
import { AuthContext } from '../../context/AuthContext';
import { Bell, Calendar, ShieldCheck, Sun, Moon } from 'lucide-react';

const Navbar = ({ activeTab }) => {
  const { user } = useContext(AuthContext);
  const [showNotif, setShowNotif] = useState(false);
  const [notifs, setNotifs] = useState([]);

  useEffect(() => {
    // Seed some role-specific notifications for visual completeness
    const getMockNotifs = () => {
      switch (user?.role) {
        case 'patient':
          return [
            { id: 1, text: 'Remember: Take Lisinopril 10mg at 9:00 AM.', type: 'pill', unread: true },
            { id: 2, text: 'Lab Report "Lipid Panel" has been verified and processed by Lisa.', type: 'report', unread: true }
          ];
        case 'doctor':
          return [
            { id: 1, text: 'New appointment scheduled: John Patient at 10:00 AM.', type: 'appointment', unread: true },
            { id: 2, text: 'Clinical audit check completed successfully.', type: 'system', unread: false }
          ];
        case 'hospital_admin':
          return [
            { id: 1, text: 'ICU Bed Allocation Alert: ICU-102 occupancy registered.', type: 'bed', unread: true },
            { id: 2, text: 'Pharmacy report: Stock level warning for Aspirin (15 units).', type: 'inventory', unread: true }
          ];
        case 'laboratory':
          return [
            { id: 1, text: 'Pending review queue: 1 new blood report file uploaded by patient.', type: 'verification', unread: true }
          ];
        case 'pharmacy':
          return [
            { id: 1, text: 'Dispense Alert: 1 new prescription generated by Dr. Heart.', type: 'prescription', unread: true }
          ];
        default:
          return [];
      }
    };
    setNotifs(getMockNotifs());
  }, [user]);

  const markAllRead = () => {
    setNotifs(notifs.map(n => ({ ...n, unread: false })));
  };

  const hasUnread = notifs.some(n => n.unread);

  const getPageTitle = () => {
    const titles = {
      overview: 'Health Overview & Analytics',
      timeline: 'Clinical Medical Timeline',
      appointments: 'Schedule & Slots',
      symptoms: 'AI Symptom Guidance',
      chat: 'AI Medical Assistant',
      patients: 'Patient Search & Directory',
      prescribe: 'Prescription Lab',
      beds: 'ICU & General Bed Manager',
      analytics: 'Hospital Performance Analytics',
      upload: 'Diagnostic Upload Portal',
      verify: 'Verification Pipeline',
      prescriptions: 'Active Prescription Queue',
      inventory: 'Medicine Inventory & Pricing',
      users: 'User Account Registry',
      logs: 'Security Event Logs'
    };
    return titles[activeTab] || 'Dashboard';
  };

  return (
    <header className="h-16 border-b border-white/5 bg-darkbg-950/80 backdrop-blur-md px-6 flex items-center justify-between sticky top-0 z-40">
      <div className="flex items-center gap-4">
        <h2 className="text-lg font-bold font-display text-slate-100">{getPageTitle()}</h2>
      </div>

      <div className="flex items-center gap-4">
        {/* Date Display */}
        <div className="hidden sm:flex items-center gap-2 px-3 py-1.5 rounded-xl bg-white/5 border border-white/5 text-xs text-slate-400">
          <Calendar className="w-3.5 h-3.5 text-medical-mint" />
          <span>{new Date().toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })}</span>
        </div>

        {/* Security Shield badge */}
        <div className="flex items-center gap-1.5 text-xs text-medical-mint font-semibold bg-medical-teal/10 px-3 py-1.5 rounded-xl border border-medical-teal/20">
          <ShieldCheck className="w-3.5 h-3.5" />
          <span className="hidden md:inline">Secure Session</span>
        </div>

        {/* Notifications Bell */}
        <div className="relative">
          <button 
            onClick={() => setShowNotif(!showNotif)}
            className="w-9 h-9 rounded-xl hover:bg-white/5 border border-transparent hover:border-white/10 flex items-center justify-center transition-colors relative"
          >
            <Bell className="w-4 h-4 text-slate-300" />
            {hasUnread && (
              <span className="absolute top-2.5 right-2.5 w-2 h-2 rounded-full bg-medical-rose animate-pulse shadow-md shadow-rose-500"></span>
            )}
          </button>

          {showNotif && (
            <div className="absolute right-0 mt-2 w-80 glass-panel border-white/10 shadow-2xl p-4 flex flex-col gap-3 animation-fade-in z-50">
              <div className="flex items-center justify-between">
                <span className="font-display font-semibold text-sm text-slate-200">Alerts & Reminders</span>
                {hasUnread && (
                  <button 
                    onClick={markAllRead} 
                    className="text-[10px] text-medical-mint font-semibold hover:underline"
                  >
                    Mark all read
                  </button>
                )}
              </div>
              <div className="flex flex-col gap-2 max-h-60 overflow-y-auto custom-scrollbar">
                {notifs.length === 0 ? (
                  <p className="text-center text-xs text-slate-500 py-4">No active reminders</p>
                ) : (
                  notifs.map(n => (
                    <div 
                      key={n.id} 
                      className={`p-2.5 rounded-xl text-xs border transition-all ${
                        n.unread 
                          ? 'bg-medical-teal/5 border-medical-teal/20 text-slate-200 font-medium' 
                          : 'bg-white/5 border-white/5 text-slate-400'
                      }`}
                    >
                      {n.text}
                    </div>
                  ))
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </header>
  );
};

export default Navbar;
